// <auto-generated />
namespace SmartRoom.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class nullablevaluerelay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullablevaluerelay));
        
        string IMigrationMetadata.Id
        {
            get { return "201809192158094_nullablevaluerelay"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
